name: JamieLab_Teaching
channels:
  - defaults
dependencies:
  - numpy = 1.21.6
  - pandas
  - matplotlib
  - seaborn
  - netCDF4
  - basemap
  - pyarrow
  - pip
  - pip:
    - pyco2sys
    - fluxengine